version: '3.8'

services:
  todo-app:
    image: jirogg/todo-app
    #command: sh -c "yarn install && yarn run dev"
    ports:
      - 5000:3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=todos
      
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos

volumes:
  mysql-data: